MarriageAgency/Models/ViewModels/InfoEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MarriageAgency.Models
{
    public class InfoEditViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Место работы")]
        public string Job { get; set; }

        [Required]
        [Display(Name = "Номер телефона")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Хобби")]
        public string? Hobby { get; set; }

        [Display(Name = "Вредные привычки")]
        public string? BadHabbits { get; set; }
        
        [Display(Name = "Паспортные данные")]
        public string? Passport { get; set; }

        [Required]
        [Display(Name = "Знак зодиака")]
        public int ZodiacSign { get; set; }

        [Required]
        [Display(Name = "Национальность")]
        public int Nationality { get; set; }

        [Required]
        [Display(Name = "Семейное положение")]
        public int FamilyStatus { get; set; }

        [Display(Name = "Адрес")]
        public string? Address { get; set; }
        
        [Display(Name = "Искомый партнер")]
        public string? DesiredPartner { get; set; }

        [Required]
        [Display(Name = "Рост")]
        public int Height { get; set; }

        [Required]
        [Display(Name = "Вес")]
        public int Weight { get; set; }

        [Required]
        [Display(Name = "Количество детей")]
        public int Children { get; set; }

        [Required]
        [Display(Name = "Пол")]
        public string Sex { get; set; }

        [Required]
        [Display(Name = "Дата рождения")]
        public DateOnly Bithdate { get; set; }
    }
}

MarriageAgency/Models/ViewModels/PaginationViewModel.cs
namespace MarriageAgency.Models
{
    public class PaginationViewModel
    {
        public int PageNumber { get; private set; }
        public int TotalPages { get; private set; }

        public bool HasPreviousPage { get; private set; }
        public bool HasNextPage { get; private set; }
        public bool HasFirstPage { get; private set; }
        public bool HasLastPage { get; private set; }

        public List<int> Pages { get; private set; }

        public PaginationViewModel(int count, int pageNumber = 1, int pageSize = 20)
        {
            PageNumber = pageNumber;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);
            
            if(TotalPages == 1)
            {
                HasPreviousPage = false;
                HasNextPage = false;
                HasFirstPage = false;
                HasLastPage = false;
                Pages = new List<int>();
            }
            else if(TotalPages < 11) 
            {
                HasPreviousPage = false;
                HasNextPage = false;
                HasFirstPage = false;
                HasLastPage = false;
                Pages = new List<int>();
                for(int i = 1; i <= TotalPages; i++)
                {
                    Pages.Add(i);
                }
            }
            else if(PageNumber < 4)
            {
                HasPreviousPage = pageNumber > 1;
                HasNextPage = true;
                HasFirstPage = false;
                HasLastPage = true;
                Pages = new List<int> { 1, 2, 3, 4, 5 };
            }
            else if (PageNumber > TotalPages - 3)
            {
                HasPreviousPage = true;
                HasNextPage = pageNumber < TotalPages;
                HasFirstPage = true;
                HasLastPage = false;
                Pages = new List<int> { TotalPages - 4, TotalPages - 3, TotalPages - 2, TotalPages - 1, TotalPages };
            }
            else
            {
                HasPreviousPage = true;
                HasNextPage = true;
                HasFirstPage = true;
                HasLastPage = true;
                Pages = new List<int> { PageNumber - 2, PageNumber - 1, PageNumber, PageNumber + 1, PageNumber + 2 };
            }
        }
    }
}

MarriageAgency/Controllers/AllServicesController.cs
using MarriageAgency.Models;
using MarriageAgency.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MarriageAgency.Controllers
{
    public class AllServicesController : Controller
    {
        MarriageAgencyContext db;
        AllServicesService allServicesService;
        public AllServicesController(MarriageAgencyContext _context, AllServicesService _allServicesService)
        {
            db = _context;
            allServicesService = _allServicesService;
        }

        public ActionResult Index()
        {
            ViewData["List"] = allServicesService.GetAllServices();
            return View();
        }
    }
}

MarriageAgency/Controllers/EmployeesController.cs
using MarriageAgency.Models;
using MarriageAgency.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MarriageAgency.Controllers
{
    public class EmployeesController : Controller
    {
        MarriageAgencyContext db;
        EmployeesService employeesService;
        public EmployeesController(MarriageAgencyContext _context, EmployeesService _employeesService)
        {
            db = _context;
            employeesService = _employeesService;
        }

        public ActionResult Index()
        {
            ViewData["List"] = employeesService.GetEmployees();
            return View();
        }
    }
}

MarriageAgency/Views/Shared/Info.cshtml
@{
    ViewData["Title"] = "Info";
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
    <h1 style="margin: 20px 0">@ViewData["ViewTitle"]</h1>
    <input type="button" class="btn btn-outline-primary" value="Изменить"
           onclick="window.location.href='@Url.Action("InfoEdit", "Account", new { clientId = ViewData["Id"]})'" />
        @if (User.IsInRole("admin"))
        {
        <input type="button" class="btn btn-outline-primary" value="Удалить"
               onclick="window.location.href='@Url.Action("Delete", "Clients", new { clientId = ViewData["Id"]})'" />
        }
    <br><br>
    <TABLE border="1" class="table table-striped">
        <TR>
            <TD>Имя</TD>
            <TD>@ViewData["Name"]</TD>
        </TR>
        <TR>
            <TD>Национальность</TD>
            <TD>@ViewData["Nationality"]</TD>
        </TR>
        <TR>
            <TD>Пол</TD>
            <TD>@ViewData["Sex"]</TD>
        </TR>
        <TR>
            <TD>Дата рождения</TD>
            <TD>@ViewData["Bithdate"]</TD>
        </TR>
        <TR>
            <TD>Рост</TD>
            <TD>@ViewData["Height"]</TD>
        </TR>
        <TR>
            <TD>Вес</TD>
            <TD>@ViewData["Weight"]</TD>
        </TR>
        <TR>
            <TD>Семейный статус</TD>
            <TD>@ViewData["FamilyStatus"]</TD>
        </TR>
        <TR>
            <TD>Дети</TD>
            <TD>@ViewData["Children"]</TD>
        </TR>
        <TR>
            <TD>Номер телефона</TD>
            <TD>@ViewData["PhoneNumber"]</TD>
        </TR>
        <TR>
            <TD>Знак зодиака</TD>
            <TD>@ViewData["ZodiacSign"]</TD>
        </TR>
        <TR>
            <TD>Работа</TD>
            <TD>@ViewData["Job"]</TD>
        </TR>
        <TR>
            <TD>Хобби</TD>
            <TD>@ViewData["Hobby"]</TD>
        </TR>
        <TR>
            <TD>Вредные привычки</TD>
            <TD>@ViewData["BadHabbits"]</TD>
        </TR>
        <TR>
            <TD>Адрес</TD>
            <TD>@ViewData["Address"]</TD>
        </TR>
        <TR>
            <TD>Пасспортные данные</TD>
            <TD>@ViewData["Passport"]</TD>
        </TR>
        <TR>
            <TD>Искомый партнер</TD>
            <TD>@ViewData["DesiredPartner"]</TD>
        </TR>
    </TABLE>
    </body>
</html>

MarriageAgency/Views/Shared/InfoEdit.cshtml
@model InfoEditViewModel

@{
    ViewData["Title"] = "Info Edit";
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div class="container col-md-8 mx-auto">
        <h2 class="mb-4 text-center">Изменение данных</h2>
        <div class="card " style="border-radius: 15px;">
            <div class="card-body">
                <form method="post" href="@Url.Action("InfoEdit", "Account", new { clientId = Model.Id})">
                    <div asp-validation-summary="ModelOnly" class="text-danger small"></div>
                    <div class="form-group mt-3">
                        <label asp-for="Name" class="control-label"></label>
                        <input type="text" asp-for="Name" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Bithdate" class="control-label"></label>
                        <input type="date" asp-for="Bithdate" min="1900-01-01" max="2005-12-19" value="@Model.Bithdate.ToString("yyyy-MM-dd")" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Bithdate"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Sex" class="control-label"></label>
                        <label class="form-check-label" for="flexRadioDefault1">
                            М
                        </label>
                        @Html.RadioButtonFor(Model => Model.Sex, "М")
                        <label class="form-check-label" for="flexRadioDefault2">
                            Ж
                        </label>
                        @Html.RadioButtonFor(Model => Model.Sex, "Ж")
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Height" class="control-label"></label>
                        <input type="number" asp-for="Height" min="120" max="220" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Height"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Weight" class="control-label"></label>
                        <input type="number" asp-for="Weight" min="35" max="350" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Weight"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Nationality" class="control-label"></label>
                        <select class="form-select" asp-for="Nationality" asp-items="@ViewBag.Nationalities"></select>
                        <span class="text-danger small" asp-validation-for="Nationality"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="ZodiacSign" class="control-label"></label>
                        <select class="form-select" asp-for="ZodiacSign" asp-items="@ViewBag.ZodiacSigns"></select>
                        <span class="text-danger small" asp-validation-for="ZodiacSign"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="FamilyStatus" class="control-label"></label>
                        <select class="form-select" asp-for="FamilyStatus" asp-items="@ViewBag.FamilyStatuses"></select>
                        <span class="text-danger small" asp-validation-for="FamilyStatus"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Children" class="control-label"></label>
                        <input type="number" asp-for="Children" min="0" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Children"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input type="string" placeholder="XX-XX-XX" pattern="[0-9]{2}-[0-9]{2}-[0-9]{2}" asp-for="PhoneNumber" class="form-control" />
                        <span class="text-danger small" asp-validation-for="PhoneNumber"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Job" class="control-label"></label>
                        <input type="text" asp-for="Job" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Job"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Hobby" class="control-label"></label>
                        <input type="text" asp-for="Hobby" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Hobby"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="BadHabbits" class="control-label"></label>
                        <input type="text" asp-for="BadHabbits" class="form-control" />
                        <span class="text-danger small" asp-validation-for="BadHabbits"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Passport" class="control-label"></label>
                        <input type="text" asp-for="Passport" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Passport"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Address" class="control-label"></label>
                        <input type="text" asp-for="Address" class="form-control" />
                        <span class="text-danger small" asp-validation-for="Address"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="DesiredPartner" class="control-label"></label>
                        <input type="text" asp-for="DesiredPartner" class="form-control" />
                        <span class="text-danger small" asp-validation-for="DesiredPartner"></span>
                    </div>
                    <div class="text-center form-group mt-3" style="margin-bottom: -5px">
                        <input type="submit" value="Изменить" class="btn btn-outline-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

MarriageAgency/Views/Shared/Pagination.cshtml
@model PaginationViewModel

<nav aria-label="...">
    <ul class="pagination">
        @if (Model.HasFirstPage)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new {pageNumber = 1})" tabindex="-1">На первую</a>
            </li>
        }
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new {pageNumber = Model.PageNumber - 1})">На предыдущую</a>
            </li>
        }
        @foreach (var number in Model.Pages)
        {
            @if (number == Model.PageNumber)
            {
                <li class="page-item active">
                    <a class="page-link" href="@Url.Action("Index", new {pageNumber = number})">@number</a>
                </li>
            }
            else
            {
                <li class="page-item"><a class="page-link" href="@Url.Action("Index", new {pageNumber = number})">@number</a></li>
            }
        }
        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new {pageNumber = Model.PageNumber + 1})">На следущую</a>
            </li>
        }
        @if (Model.HasLastPage)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new {pageNumber = Model.TotalPages})">На последнюю</a>
            </li>
        }
    </ul>
</nav>

MarriageAgency/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarriageAgency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarriageAgency.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">На главную</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AllServices" asp-action="Index">Услуги</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("client"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ProvidedServices" asp-action="Index">Мои заказы</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Info">@User.Identity.Name</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ProvidedServices" asp-action="Index">Оказанные услуги</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Клиенты</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Зарегистрироваться</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MarriageAgency
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>